version: '3.1'
services:
  app:
    container_name: employeproject-postgres-compose
    image: employeproject-postgres-compose
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - postgresqldb
  postgresqldb:
    image: postgres 
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=omsairam
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgresdb
